#!/usr/bin/env bash
# ============================================================================
# moodle-deploy: Deploy Moodle plugins to a local Docker-in-Orb environment
# ============================================================================
# Auto-detects: Orb VM → Docker container → Moodle webroot
# Then copies plugin files and runs upgrade + cache purge.
#
# Usage:
#   bash deploy.sh --source /path/to/plugin/dir [options]
#
# See --help for all options.
# ============================================================================

set -euo pipefail

# ---------- Defaults ----------
SOURCE_DIR=""
ORB_VM=""
CONTAINER=""
WEBROOT=""
HOST_WEBROOT=""        # auto-detected from bind mounts; when set, enables fast host-side copy
DRY_RUN=false
SKIP_UPGRADE=false
SKIP_CACHE=false
PHPUNIT_INIT=false
VERBOSE=false
NATIVE_DOCKER=false
CONFIG_FILE="$HOME/.moodle-deploy.conf"

# ---------- Colors ----------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# ---------- Helpers ----------
info()    { echo -e "${BLUE}ℹ${NC}  $*"; }
success() { echo -e "${GREEN}✓${NC}  $*"; }
warn()    { echo -e "${YELLOW}⚠${NC}  $*"; }
error()   { echo -e "${RED}✗${NC}  $*" >&2; }
step()    { echo -e "\n${BOLD}${CYAN}▸ $*${NC}"; }
debug()   { $VERBOSE && echo -e "  ${CYAN}→${NC} $*" || true; }

die() { error "$*"; exit 1; }

# ---------- Parse arguments ----------
show_help() {
    cat <<'EOF'
Usage: deploy.sh --source <dir> [options]

Required:
  --source <path>       Directory containing plugin(s) in Moodle layout
                        (e.g., with mod/, blocks/, local/ subdirectories)

Environment (auto-detected if not provided):
  --orb <name>          Orb VM name (or "native" for OrbStack native Docker)
  --container <name>    Docker container name/ID
  --webroot <path>      Moodle webroot path INSIDE the container
  --host-webroot <path> Moodle webroot path ON THE MAC (auto-detected from
                        bind mounts). When set, files are copied directly
                        on the host — skips docker cp entirely.
  --no-host-copy        Force docker cp mode even if a bind mount exists

Behavior:
  --dry-run             Show what would happen, don't change anything
  --skip-upgrade        Copy files but don't run admin/cli/upgrade.php
  --skip-cache          Don't purge caches after deployment
  --phpunit-init        Run admin/tool/phpunit/cli/init.php after deploy
  --verbose             Detailed output
  --no-config           Don't read or save ~/.moodle-deploy.conf
  --help                Show this help

Examples:
  # Auto-detect everything, deploy plugin
  deploy.sh --source ./my-plugin

  # Dry run first
  deploy.sh --source ./my-plugin --dry-run

  # Deploy + prepare PHPUnit test DB
  deploy.sh --source ./my-plugin --phpunit-init

  # Explicit environment (skip detection)
  deploy.sh --source ./my-plugin \
    --container demo-webserver-1 \
    --webroot /var/www/site/moodle \
    --host-webroot ~/demo/site/moodle
EOF
    exit 0
}

NO_CONFIG=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --source)       SOURCE_DIR="$2"; shift 2 ;;
        --orb)          ORB_VM="$2"; shift 2 ;;
        --container)    CONTAINER="$2"; shift 2 ;;
        --webroot)      WEBROOT="$2"; shift 2 ;;
        --host-webroot) HOST_WEBROOT="$2"; shift 2 ;;
        --no-host-copy) HOST_WEBROOT="__DISABLED__"; shift ;;
        --dry-run)      DRY_RUN=true; shift ;;
        --skip-upgrade) SKIP_UPGRADE=true; shift ;;
        --skip-cache)   SKIP_CACHE=true; shift ;;
        --phpunit-init) PHPUNIT_INIT=true; shift ;;
        --verbose)      VERBOSE=true; shift ;;
        --no-config)    NO_CONFIG=true; shift ;;
        --help|-h)      show_help ;;
        *) die "Unknown option: $1. Use --help for usage." ;;
    esac
done

[[ -z "$SOURCE_DIR" ]] && die "Missing --source. Use --help for usage."
[[ ! -d "$SOURCE_DIR" ]] && die "Source directory does not exist: $SOURCE_DIR"

# ---------- Load saved config ----------
load_config() {
    if [[ "$NO_CONFIG" == true ]] || [[ ! -f "$CONFIG_FILE" ]]; then
        return
    fi
    debug "Loading saved config from $CONFIG_FILE"
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
    # Only use saved values if not explicitly provided
    [[ -z "$ORB_VM" ]] && ORB_VM="${SAVED_ORB_VM:-}"
    [[ -z "$CONTAINER" ]] && CONTAINER="${SAVED_CONTAINER:-}"
    [[ -z "$WEBROOT" ]] && WEBROOT="${SAVED_WEBROOT:-}"
    [[ -z "$HOST_WEBROOT" ]] && HOST_WEBROOT="${SAVED_HOST_WEBROOT:-}"
    [[ "${SAVED_NATIVE_DOCKER:-false}" == true ]] && NATIVE_DOCKER=true
}

save_config() {
    if [[ "$NO_CONFIG" == true ]] || [[ "$DRY_RUN" == true ]]; then
        return
    fi
    cat > "$CONFIG_FILE" <<EOF
# Auto-generated by moodle-deploy on $(date -Iseconds)
SAVED_ORB_VM="$ORB_VM"
SAVED_CONTAINER="$CONTAINER"
SAVED_WEBROOT="$WEBROOT"
SAVED_HOST_WEBROOT="$HOST_WEBROOT"
SAVED_NATIVE_DOCKER="$NATIVE_DOCKER"
EOF
    debug "Saved config to $CONFIG_FILE"
}

# ---------- Step 1: Find Orb VM (or switch to native Docker mode) ----------
detect_orb_vm() {
    step "Detecting Orb VM"

    if [[ -n "$ORB_VM" ]]; then
        info "Using provided VM: $ORB_VM"
        return
    fi

    if ! command -v orb &>/dev/null; then
        # No orb CLI — try native Docker
        if command -v docker &>/dev/null && docker info &>/dev/null; then
            success "No Orb CLI — using native Docker"
            NATIVE_DOCKER=true
            return
        fi
        die "orb command not found and native Docker not available. Is Orb/Docker installed?"
    fi

    # Get list of running VMs. Orb 2.x output has columns:
    # NAME  STATE  DISTRO  VERSION  ARCH  SIZE  IP
    # followed by a separator row of dashes — skip header AND dashes.
    local vms
    vms=$(orb list 2>/dev/null \
        | awk 'NR>2 && $1 !~ /^-+$/ && $2 ~ /running/i {print $1}' \
        || true)

    if [[ -z "$vms" ]]; then
        # No Orb VM — fall back to native Docker (OrbStack native Docker mode,
        # or plain Docker Desktop, etc.)
        if command -v docker &>/dev/null && docker info &>/dev/null; then
            success "No Orb VM found — using native Docker (OrbStack native mode)"
            NATIVE_DOCKER=true
            return
        fi
        die "No running Orb VMs found and native Docker not available. Start your VM first (orb start <name>) or make sure Docker runs natively."
    fi

    local count
    count=$(echo "$vms" | wc -l | tr -d ' ')

    if [[ "$count" -eq 1 ]]; then
        ORB_VM=$(echo "$vms" | head -1)
        success "Found Orb VM: $ORB_VM"
    else
        warn "Multiple running VMs found:"
        echo "$vms" | while read -r vm; do echo "  - $vm"; done
        # Use the first one
        ORB_VM=$(echo "$vms" | head -1)
        warn "Using first VM: $ORB_VM (override with --orb <name>)"
    fi
}

# Helper: run a command — inside the Orb VM, or directly in native Docker mode
orb_exec() {
    if [[ "$NATIVE_DOCKER" == true ]]; then
        "$@"
    else
        orb -m "$ORB_VM" "$@"
    fi
}

# ---------- Step 2: Find Docker container ----------
detect_container() {
    step "Detecting Moodle Docker container"

    if [[ -n "$CONTAINER" ]]; then
        info "Using provided container: $CONTAINER"
        return
    fi

    # List running containers, look for moodle-related ones
    local containers
    containers=$(orb_exec docker ps --format '{{.Names}}\t{{.Image}}' 2>/dev/null || true)

    if [[ -z "$containers" ]]; then
        die "No running Docker containers found in VM '$ORB_VM'. Is Docker running? Try: orb -m $ORB_VM docker compose up -d"
    fi

    debug "Running containers:"
    $VERBOSE && echo "$containers" | sed 's/^/    /' || true

    # Try to find a Moodle container by image name or container name.
    # Match common Moodle patterns: moodle, mdc- (moodle-docker-compose),
    # bitnami/moodle, plus webserver/apache/php-fpm names when paired with
    # a Moodle-ish image.
    local moodle_containers=""

    while IFS=$'\t' read -r name image; do
        if echo "$name $image" | grep -qiE "moodle|mdc-php|bitnami/moodle|php-apache|webserver"; then
            moodle_containers="${moodle_containers}${name}\n"
        fi
    done <<< "$containers"

    moodle_containers=$(echo -e "$moodle_containers" | sed '/^$/d')

    if [[ -z "$moodle_containers" ]]; then
        warn "No Moodle-like container found by name/image pattern."
        warn "Available containers:"
        echo "$containers" | while IFS=$'\t' read -r name image; do
            echo "    $name ($image)"
        done
        die "Specify the container with --container <name>"
    fi

    # Exclude satellites (db, selenium, redis, etc.) — keep only the app/webserver
    local app_containers
    app_containers=$(echo "$moodle_containers" \
        | grep -vi -e "db" -e "postgres" -e "mysql" -e "mariadb" \
                   -e "redis" -e "memcache" -e "selenium" -e "chrome" \
                   -e "firefox" -e "mail" -e "smtp" || true)
    # If the exclusion dropped everything, fall back to the original list
    [[ -z "$app_containers" ]] && app_containers="$moodle_containers"

    local count
    count=$(echo "$app_containers" | wc -l | tr -d ' ')

    if [[ "$count" -eq 1 ]]; then
        CONTAINER=$(echo "$app_containers" | head -1)
        success "Found Moodle container: $CONTAINER"
    else
        warn "Multiple Moodle-related app containers found:"
        echo "$app_containers" | while read -r c; do echo "  - $c"; done
        CONTAINER=$(echo "$app_containers" | head -1)
        warn "Using: $CONTAINER (override with --container <name>)"
    fi
}

# Helper: run a command inside the Docker container (via Orb)
docker_exec() {
    orb_exec docker exec "$CONTAINER" "$@"
}

# ---------- Step 3: Find Moodle webroot ----------
# Uses admin/cli/upgrade.php as the anchor (NOT config.php) because some
# Moodle 5.x checkouts have a stub public/config.php that is not the real
# webroot — the authoritative location is wherever the CLI scripts live.
detect_webroot() {
    step "Detecting Moodle webroot"

    if [[ -n "$WEBROOT" ]]; then
        info "Using provided webroot: $WEBROOT"
        return
    fi

    # Check common Moodle paths inside the container.
    local candidates=(
        # Moodle 5.x with public/ layout
        "/var/www/site/moodle/public"
        "/var/www/html/moodle/public"
        "/var/www/moodle/public"
        "/bitnami/moodle/public"
        # Classic (pre-5.x) layouts
        "/bitnami/moodle"
        "/var/www/html"
        "/var/www/html/moodle"
        "/var/www/site/moodle"
        "/var/www/moodle"
        "/opt/moodle"
        "/app/moodle"
    )

    for path in "${candidates[@]}"; do
        if docker_exec test -f "$path/admin/cli/upgrade.php" 2>/dev/null; then
            WEBROOT="$path"
            success "Found Moodle webroot: $WEBROOT"
            return
        fi
    done

    # Last resort: find admin/cli/upgrade.php anywhere
    info "Candidates exhausted — searching for admin/cli/upgrade.php..."
    local found
    found=$(docker_exec find /var/www /opt /app -maxdepth 6 \
        -name upgrade.php -path "*admin/cli*" 2>/dev/null | head -1 || true)

    if [[ -n "$found" ]]; then
        # upgrade.php is at <webroot>/admin/cli/upgrade.php → strip 3 levels
        WEBROOT=$(dirname "$(dirname "$(dirname "$found")")")
        success "Found Moodle webroot (via search): $WEBROOT"
        return
    fi

    die "Could not find Moodle webroot. Specify it with --webroot <path>"
}

# ---------- Step 3b: Auto-detect bind-mounted webroot on the host ----------
# If the container's WEBROOT is inside a bind mount, compute the host path so
# we can copy files directly on the Mac side (faster + bypasses docker cp
# /tmp-namespace weirdness seen with OrbStack native Docker).
detect_host_webroot() {
    # Skip if explicitly disabled
    if [[ "$HOST_WEBROOT" == "__DISABLED__" ]]; then
        HOST_WEBROOT=""
        info "Host-side copy disabled (--no-host-copy)"
        return
    fi

    # Skip if already provided
    if [[ -n "$HOST_WEBROOT" ]]; then
        info "Using provided host webroot: $HOST_WEBROOT"
        return
    fi

    step "Checking for bind-mounted webroot (fast-path)"

    # Get all bind mounts: "<source>\t<destination>" per line
    local mounts
    mounts=$(orb_exec docker inspect "$CONTAINER" \
        --format '{{range .Mounts}}{{if eq .Type "bind"}}{{.Source}}{{"\t"}}{{.Destination}}{{"\n"}}{{end}}{{end}}' \
        2>/dev/null || true)

    if [[ -z "$mounts" ]]; then
        info "No bind mounts found — using docker cp for file transfer"
        return
    fi

    debug "Bind mounts in container:"
    $VERBOSE && echo "$mounts" | sed 's/^/    /' || true

    # Find the most specific bind mount whose destination is a prefix of WEBROOT.
    # "Most specific" = longest destination path.
    local best_src="" best_dst="" dst_len=0
    while IFS=$'\t' read -r src dst; do
        [[ -z "$src" || -z "$dst" ]] && continue
        # Check if WEBROOT is inside this mount destination
        if [[ "$WEBROOT" == "$dst" || "$WEBROOT" == "$dst"/* ]]; then
            if (( ${#dst} > dst_len )); then
                best_src="$src"
                best_dst="$dst"
                dst_len=${#dst}
            fi
        fi
    done <<< "$mounts"

    if [[ -z "$best_src" ]]; then
        info "Webroot $WEBROOT is not inside any bind mount — using docker cp"
        return
    fi

    # Compute host path: replace the destination prefix with the source prefix
    local suffix="${WEBROOT#$best_dst}"
    HOST_WEBROOT="${best_src}${suffix}"

    if [[ -d "$HOST_WEBROOT" ]]; then
        success "Bind mount detected: $best_dst → $best_src"
        success "Host webroot: $HOST_WEBROOT (fast-path enabled)"
    else
        warn "Computed host webroot doesn't exist on the Mac: $HOST_WEBROOT"
        warn "Falling back to docker cp"
        HOST_WEBROOT=""
    fi
}

# ---------- Step 4: Discover plugins to deploy ----------
discover_plugins() {
    step "Discovering plugins in source directory"

    PLUGINS=()

    # Look for standard Moodle plugin directories
    local plugin_types=("mod" "blocks" "local" "theme" "auth" "enrol" "report"
                        "filter" "format" "question" "admin" "availability"
                        "plagiarism" "repository" "tool" "grade")

    for ptype in "${plugin_types[@]}"; do
        if [[ -d "$SOURCE_DIR/$ptype" ]]; then
            for plugin_dir in "$SOURCE_DIR/$ptype"/*/; do
                if [[ -d "$plugin_dir" ]]; then
                    local plugin_name
                    plugin_name=$(basename "$plugin_dir")
                    # Verify it looks like a Moodle plugin (has version.php)
                    if [[ -f "$plugin_dir/version.php" ]]; then
                        PLUGINS+=("$ptype/$plugin_name")
                        success "Found: $ptype/$plugin_name"
                    else
                        warn "Skipping $ptype/$plugin_name (no version.php)"
                    fi
                fi
            done
        fi
    done

    # Also check if the source dir itself is a plugin
    if [[ ${#PLUGINS[@]} -eq 0 ]] && [[ -f "$SOURCE_DIR/version.php" ]]; then
        # Try to determine plugin type from version.php
        local component
        component=$(grep -oP "\\\$plugin->component\s*=\s*'([^']+)'" "$SOURCE_DIR/version.php" | grep -oP "'[^']+'" | tr -d "'" || true)
        if [[ -n "$component" ]]; then
            local ptype pname
            ptype=$(echo "$component" | cut -d_ -f1)
            pname=$(echo "$component" | cut -d_ -f2-)
            # Map component prefix to directory
            case "$ptype" in
                mod)    PLUGINS+=("mod/$pname") ;;
                block)  PLUGINS+=("blocks/$pname") ;;
                local)  PLUGINS+=("local/$pname") ;;
                *)      PLUGINS+=("$ptype/$pname") ;;
            esac
            success "Found standalone plugin: ${PLUGINS[-1]}"
        fi
    fi

    if [[ ${#PLUGINS[@]} -eq 0 ]]; then
        die "No Moodle plugins found in $SOURCE_DIR. Expected directories like mod/<name>/, blocks/<name>/, etc."
    fi

    info "Total plugins to deploy: ${#PLUGINS[@]}"
}

# ---------- Step 5: Copy files ----------
# Two modes:
# A) Bind-mount fast path (HOST_WEBROOT set): rsync directly to host path.
#    Fastest, bypasses the OrbStack docker cp /tmp namespace bug entirely.
# B) Container copy path (no bind mount): tar archive, docker cp to /var/tmp
#    (NOT /tmp — OrbStack sometimes can't see /tmp files across exec calls),
#    extract inside container.
deploy_plugins() {
    step "Deploying plugins"

    for plugin in "${PLUGINS[@]}"; do
        local src_path="$SOURCE_DIR/$plugin"
        local dest_path="$WEBROOT/$plugin"

        info "Deploying $plugin → $dest_path"

        if [[ "$DRY_RUN" == true ]]; then
            if [[ -n "$HOST_WEBROOT" ]]; then
                info "[DRY RUN] Would rsync $src_path/ → $HOST_WEBROOT/$plugin/ (host fast-path)"
            else
                info "[DRY RUN] Would copy $src_path → container:$dest_path via tar/docker cp"
            fi
            local file_count
            file_count=$(find "$src_path" -type f | wc -l | tr -d ' ')
            debug "  $file_count files to copy"
            continue
        fi

        if [[ -n "$HOST_WEBROOT" ]]; then
            # ---------- Mode A: bind-mount host-side rsync ----------
            local host_dest="$HOST_WEBROOT/$plugin"
            debug "Fast-path: rsync → $host_dest"
            mkdir -p "$(dirname "$host_dest")"
            # --delete to remove files that no longer exist in source
            if command -v rsync &>/dev/null; then
                rsync -a --delete "$src_path/" "$host_dest/"
            else
                # Fallback if rsync isn't installed
                rm -rf "$host_dest"
                mkdir -p "$host_dest"
                cp -R "$src_path/." "$host_dest/"
            fi
            # Fix ownership inside the container so Apache can read the files
            debug "Fixing permissions inside container..."
            docker_exec chown -R www-data:www-data "$dest_path" 2>/dev/null || \
            docker_exec chown -R daemon:daemon "$dest_path" 2>/dev/null || \
            docker_exec chmod -R 755 "$dest_path" 2>/dev/null || true

            success "Deployed (fast-path): $plugin"
            continue
        fi

        # ---------- Mode B: classic docker cp ----------
        debug "Removing old version: $dest_path"
        docker_exec rm -rf "$dest_path" 2>/dev/null || true

        local parent_dir
        parent_dir=$(dirname "$dest_path")
        docker_exec mkdir -p "$parent_dir" 2>/dev/null || true

        # Use /var/tmp instead of /tmp to avoid the OrbStack /tmp namespace bug.
        local host_tar="$(mktemp -t moodle-deploy.XXXXXX.tar)"
        local container_tar="/var/tmp/moodle-deploy-$$.tar"
        debug "Creating archive: $host_tar"
        (cd "$SOURCE_DIR" && tar cf "$host_tar" "$plugin")

        debug "Copying tar into container: $container_tar"
        orb_exec docker cp "$host_tar" "$CONTAINER:$container_tar"

        debug "Extracting in container..."
        docker_exec tar xf "$container_tar" -C "$WEBROOT/"
        docker_exec rm -f "$container_tar"
        rm -f "$host_tar"

        debug "Fixing permissions..."
        docker_exec chown -R www-data:www-data "$dest_path" 2>/dev/null || \
        docker_exec chown -R daemon:daemon "$dest_path" 2>/dev/null || \
        docker_exec chmod -R 755 "$dest_path" 2>/dev/null || true

        success "Deployed: $plugin"
    done
}

# ---------- Step 6: Run Moodle CLI ----------
run_upgrade() {
    if [[ "$SKIP_UPGRADE" == true ]]; then
        info "Skipping upgrade (--skip-upgrade)"
        return
    fi

    step "Running Moodle upgrade"

    if [[ "$DRY_RUN" == true ]]; then
        info "[DRY RUN] Would run: php admin/cli/upgrade.php --non-interactive"
        return
    fi

    # Determine the PHP user (varies by Docker image)
    local php_user="www-data"
    if docker_exec id daemon &>/dev/null; then
        # Bitnami images use 'daemon'
        if docker_exec test -d /bitnami 2>/dev/null; then
            php_user="daemon"
        fi
    fi

    info "Running upgrade as $php_user..."
    local output
    if output=$(orb_exec docker exec -u "$php_user" "$CONTAINER" \
        php "$WEBROOT/admin/cli/upgrade.php" --non-interactive 2>&1); then
        success "Upgrade completed successfully"
        $VERBOSE && echo "$output" | tail -20 | sed 's/^/    /' || true
    else
        local exit_code=$?
        warn "Upgrade exited with code $exit_code"
        echo "$output" | tail -30 | sed 's/^/    /'
        # Don't die — some exit codes are benign (e.g., "nothing to upgrade")
        if echo "$output" | grep -qi "error\|fatal\|exception"; then
            error "Upgrade had errors — check the output above"
        else
            info "This is likely OK (nothing new to upgrade)"
        fi
    fi
}

purge_caches() {
    if [[ "$SKIP_CACHE" == true ]]; then
        info "Skipping cache purge (--skip-cache)"
        return
    fi

    step "Purging Moodle caches"

    if [[ "$DRY_RUN" == true ]]; then
        info "[DRY RUN] Would run: php admin/cli/purge_caches.php"
        return
    fi

    local php_user="www-data"
    if docker_exec test -d /bitnami 2>/dev/null; then
        php_user="daemon"
    fi

    if docker_exec php "$WEBROOT/admin/cli/purge_caches.php" 2>&1; then
        success "Caches purged"
    else
        warn "Cache purge had issues (may be non-critical)"
    fi
}

run_phpunit_init() {
    if [[ "$PHPUNIT_INIT" != true ]]; then
        return
    fi

    step "Initializing PHPUnit test environment"

    if [[ "$DRY_RUN" == true ]]; then
        info "[DRY RUN] Would run: php admin/tool/phpunit/cli/init.php"
        return
    fi

    info "This may take a minute..."
    if docker_exec php "$WEBROOT/admin/tool/phpunit/cli/init.php" 2>&1; then
        success "PHPUnit initialized"
    else
        warn "PHPUnit init had issues — check if phpunit is configured in config.php"
    fi
}

# ---------- Main ----------
main() {
    echo -e "\n${BOLD}🚀 Moodle Deploy${NC}"
    echo -e "───────────────────────────────────\n"

    if [[ "$DRY_RUN" == true ]]; then
        warn "DRY RUN MODE — no changes will be made\n"
    fi

    load_config
    detect_orb_vm
    detect_container
    detect_webroot
    detect_host_webroot
    discover_plugins

    echo ""
    info "Environment summary:"
    if [[ "$NATIVE_DOCKER" == true ]]; then
        echo -e "    Orb VM:     ${BOLD}(native Docker — no VM)${NC}"
    else
        echo -e "    Orb VM:     ${BOLD}$ORB_VM${NC}"
    fi
    echo -e "    Container:  ${BOLD}$CONTAINER${NC}"
    echo -e "    Webroot:    ${BOLD}$WEBROOT${NC}"
    if [[ -n "$HOST_WEBROOT" ]]; then
        echo -e "    Host path:  ${BOLD}$HOST_WEBROOT${NC} ${CYAN}(fast-path)${NC}"
    fi
    echo -e "    Plugins:    ${BOLD}${PLUGINS[*]}${NC}"
    echo ""

    deploy_plugins
    run_upgrade
    purge_caches
    run_phpunit_init

    # Save config for next time
    save_config

    echo ""
    if [[ "$DRY_RUN" == true ]]; then
        success "${BOLD}Dry run complete.${NC} Rerun without --dry-run to deploy."
    else
        success "${BOLD}Deployment complete!${NC}"
        info "Open your Moodle in the browser to verify."
        info "Config saved to $CONFIG_FILE for faster future deploys."
    fi
}

main
